name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 2'  # every Tuesday at 9 am UTC

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: maven

      - name: Build with Maven
        run: ./mvnw clean verify

      - name: Set up Git actions user
        uses: fregante/setup-git-user@v1

      - name: Create release tag
        run: |
          git tag "v$(git show -s --format=%cd --date=format:%Y%m%d.%H%M%S)"
          git push --tags

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1

      - name: Create release
        if: ${{ !env.ACT }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.createTag.outputs.tagName }}"
          release_name: "v${{ steps.createTag.outputs.tagName }}"
          draft: false
          prerelease: false
          body: '${{ steps.extract-release-notes.outputs.release_notes }}'
